### ISSUE TITLE
Game List?

### ISSUE THREAD

**Issue by orangemn6** [Ghost0159/Ghost-Eshop-Alternative-3ds#13]
I remember a couple of days ago there was a website with an RSS feed of all the games. Can you please bring that back? also is pokemon X on this eshop?

**Comment by Ghost0159** [comment]
We are in the process of redoing the site, as well as the homebrew, the new homebrew with better image, description ...
https://ghosteshop.tk/

**Comment by orangemn6** [comment]
ok thank you very much. can you keep me updated here?

**Comment by Ghost0159** [comment]
New adress: http://ghosteshop.com/

**Comment by Ghost0159** [comment]
Available in a few hours
