### ISSUE TITLE
Add filter by region and by language

### ISSUE THREAD

**Issue by wuniversales** [Ghost0159/Ghost-Eshop-Alternative-3ds#14]
Well, the title says it all, I don't think it needs to be explained XD

**Comment by Ghost0159** [comment]
We can already sort by region, title, category, console

**Comment by DarkUwU123** [comment]
cc

**Comment by Ghost0159** [comment]
![TRIE1](https://user-images.githubusercontent.com/66320002/97729949-82370e80-1ad3-11eb-84cd-fc337fceca60.jpg)
![TRIE2](https://user-images.githubusercontent.com/66320002/97729952-83683b80-1ad3-11eb-9c6c-8082a1476519.jpg)
![TTRIE3](https://user-images.githubusercontent.com/66320002/97729954-8400d200-1ad3-11eb-835b-ac01b29bb163.jpg)

**Comment by wuniversales** [comment]
You cannot by region ... Pal, Jap, etc ...

**Comment by Ghost0159** [comment]
Not by region, sorry ;P

**Comment by Ghost0159** [comment]
For the futur version
