### ISSUE TITLE
Use IPFS or Blockchain to host the files and website

### ISSUE THREAD

**Issue by wuniversales** [Ghost0159/Ghost-Eshop-Alternative-3ds#15]
I think it would be nice to use IPFS or Blockchain to host the files and website.
I leave you because here a very useful hosting based on blockstack.
https://runkod.com/
Greetings

**Comment by Ghost0159** [comment]
Alredy exist: https://ghosteshop.com/

**Comment by Ghost0159** [comment]
For exemple: https://cdn.ghosteshop.com/Juegos%203DS/EUR/W/WRC%202014%20FIA%20World%20Rally%20Championship%20%28EUR%29.cia

**Comment by wuniversales** [comment]
I meant that you use a decentralized hosting...
Cheers
