### ISSUE TITLE
About the screenshots

### ISSUE THREAD

**Issue by NightYoshi370** [Ghost0159/Ghost-Eshop-Alternative-3ds#7]
Hey bro, thanks for your cooperation with disbanding yourselves from Universal Team. It means a lot to us that you specified our stance on piracy and plan to make your own app. However, for the meantime, could you remove those screenshots from the ReadME file?

Thanks once again
~NightScript, member of Universal Team

**Comment by Ghost0159** [comment]
I will do this tomorrow, thank you for your request, for now the homebrew is at the development stage, these are just lines of code that use in 3DSLINK with the homebrew launcher, a developer is working on everything.
During this time I continue the script, and I start to think about making it incompatible with Universal-Updater when the time comes.
Ps: Sorry for the English, I'm French.

**Comment by MeatReed** [comment]
good luck guest

**Comment by Ghost0159** [comment]
Screnshot delete
